name: 'setup nodejs'

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        run_install: true

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4.2.4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts

    - name: Build project
      shell: bash
      run: |
        pnpm run build
      env:
        CI: true
