name: 'Build nut image'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: docker/build-push-action@v6
      with:
        file: .github/tests/Dockerfile
        tags: nut-test:latest
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/nut-test.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-nut
        path: /tmp/nut-test.tar
