name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/build-nut-image

  build:
    permissions:
      checks: write
      actions: read
      contents: read
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [22, lts/*, 26]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - uses: yogeshlonkar/wait-for-jobs@69a4ff07c63e4f28c8abe4fa4fe6d5aed8fc2147 # v1
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          jobs: 'build-docker'

      - uses: ./.github/actions/run-tests
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: run eslint
        run: |
          npm run ci:eslint
        continue-on-error: true
        env:
          CI: true

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage
          path: |
            ./coverage/coverage-final.json
            ./coverage/lcov.info
            ./coverage/eslint-report.json
        if: ${{ matrix.node-version == 'lts/*' }}

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          directory: ./coverage
        if: ${{ matrix.node-version == 'lts/*' }}

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarqube-scan-action@v5.3.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: -Dsonar.projectName=nut
      #   if: ${{ matrix.node-version == 'lts/*' }}
